language: python
python:
  - "3.6"
notifications:
  email:
    on_success: never
    on_failure: never
before_install:
  - python setup.py install
install:
  - pip install bs4
  - pip install requests
  - pip install lxml
  - pip install tqdm
script:
  - python lingcorpora/test_lc.py
