language: python
python:
  - "3.5"
 notifications:
  email:
    on_success: never
    on_failure: never
install:
  - pip install bs4
  - pip install requests
  - pip install lxml
  - pip install tqdm
script:
  - python test_lingcorpora/test_lc.py
